### ISSUE TITLE
Doubt regarding predictions

### ISSUE THREAD

**Issue by ayushmaan-IIITD** [fmpr/Combining-TimeSeries-TextData#1]
I wanted to know if there is a way that I can make the model predict for next 'Xth' day by changing any parameter in the model?
Thanks in advance.

Regards
Ayushmaan Kaul

**Comment by fmpr** [comment]
Hi @ayushmaan-IIITD, the model in the demo is a one-step-ahead prediction model - i.e. you fit it with the last k observations (from time t-k to time t), and use the model to make a prediction for t+1. The simplest way in which you can modify the model to make predictions for multiple steps ahead is by changing the output layer to have multiple output variables, and changing the input and target variables that you use to train the model accordingly. Alternatively, you can look into more complex architectures like Encoder-Decoder architectures. But it seems that your question is general "neural network architectures for time-series forecasting" question, rather than something specific to this model. I suggest that you have a look at a tutorial on this topic like, for example, this one: https://machinelearningmastery.com/how-to-develop-lstm-models-for-multi-step-time-series-forecasting-of-household-power-consumption/ 
I hope it helps.
